# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
project_name: orbitd
report_sizes: true

before:
  hooks:
    - go mod tidy
    - go fmt ./...
    - go vet ./...
    - go test ./...

gomod:
  proxy: true

builds:
  - binary: "{{ .ProjectName }}"
    env: [CGO_ENABLED=0]
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{ .CommitDate }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

upx:
  - enabled: true
    lzma: true
    compress: best
    goos: [linux]

kos:
  - base_image: alpine
    repositories: [ghcr.io/mizuchilabs/orbitd]
    bare: true
    preserve_import_paths: false
    sbom: none
    creation_time: "{{ .CommitTimestamp }}"
    tags:
      - "{{ .Version }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64

signs:
  - cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--yes"
      - "${artifact}"
      - "--bundle=${signature}"

sboms:
  - cmd: syft
    documents:
      - "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}.sbom.json"
    args: ["$artifact", "--output", "cyclonedx-json=$document"]
    artifacts: binary

source:
  enabled: true

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
  mode: keep-existing

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
      - "^sec:"
      - "^perf:"
      - "^docs:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Security
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Other
      order: 999
