version: "3"

output: prefixed

env:
  CGO_ENABLED: 0
  IMAGE_PROD: ghcr.io/mizuchilabs/orbitd

tasks:
  dev:
    desc: Run command in dev mode
    cmds:
      - go run cmd/main.go
    silent: false

  # 󰚰 Update deps
  update:
    desc: Update dependencies
    cmds:
      - go get -u ./...

  #   Build
  build:
    desc: Build binary
    cmds:
      - go build -ldflags="-s -w" -trimpath -o bin/orbitd ./cmd/main.go

  # 󰉠  Lint / static checks
  lint:
    desc: Run go vet & lint
    cmds:
      - go mod tidy
      - go fmt ./...
      - go vet ./...
      - go test ./...

  snapshot:
    desc: Build snapshot
    cmds:
      - goreleaser --snapshot --clean --skip=validate

  # 󱓞  Release
  release:
    desc: Build release
    deps: [lint]
    cmds:
      - goreleaser release --clean --skip=validate

  docker:push:
    desc: Build and push container to registry
    cmds:
      - goreleaser release --clean --skip=publish,validate,sign,sbom,archive
      - grype $IMAGE_PROD
