name: Test

on:
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Lint and test
        run: |
          go mod tidy
          go mod verify
          go fmt ./...
          go vet ./...
          go test ./...

      - uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=10m

      - name: Build
        run: go build -ldflags="-s -w" -o bin/

      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-tagged: 10
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
          delete-orphaned-images: true
          token: ${{ secrets.GITHUB_TOKEN }}
